export interface DestinationSearchOption {
  name: string;
  region: string;
}

export const DESTINATION_SEARCH_OPTIONS: DestinationSearchOption[] = [
  {"name": "Agartala", "region": "Tripura, India"},
  {"name": "Agra", "region": "India"},
  {"name": "Agra", "region": "Uttar Pradesh, India"},
  {"name": "Ahmedabad", "region": "Gujarat, India"},
  {"name": "Ajanta", "region": "Maharashtra, India"},
  {"name": "Ajmer", "region": "Rajasthan, India"},
  {"name": "Alappuzha", "region": "Kerala, India"},
  {"name": "Alibaug", "region": "Maharastra, India"},
  {"name": "Aligarh", "region": "Uttar Pradesh, India"},
  {"name": "Allahabad", "region": "Uttar Pradesh, India"},
  {"name": "Almora", "region": "Uttarakhand, India"},
  {"name": "Amarkantak", "region": "Madhya Pradesh, India"},
  {"name": "Amravati", "region": "Andhra Pradesh, India"},
  {"name": "Amritsar", "region": "Punjab, India"},
  {"name": "Anantapur", "region": "Andhra Pradesh, India"},
  {"name": "Anantnag", "region": "Jammu and Kashmir, India"},
  {"name": "Andaman", "region": "India"},
  {"name": "Auli", "region": "Uttarakhand, India"},
  {"name": "Aurangabad", "region": "Maharastra, India"},
  {"name": "Auroville", "region": "Puducherry, India"},
  {"name": "Ayodhya", "region": "Uttar Pradesh, India"},
  {"name": "Badami", "region": "Karnataka, India"},
  {"name": "Badrinath", "region": "Uttarakhand, India"},
  {"name": "Balasore", "region": "Odisha, India"},
  {"name": "Bandhavgarh", "region": "Madhya Pradesh, India"},
  {"name": "Bandipur", "region": "Karnataka, India"},
  {"name": "Bangalore", "region": "Karnataka, India"},
  {"name": "Baratang Island", "region": "Andaman and Nicobar Islands, India"},
  {"name": "Barot", "region": "Himachal Pradesh, India"},
  {"name": "Bastar", "region": "Chhattisgarh, India"},
  {"name": "Bekal", "region": "Kerala, India"},
  {"name": "Bengaluru", "region": "Karnataka, India"},
  {"name": "Berhampur", "region": "Odisha, India"},
  {"name": "Bhimbetka", "region": "Madhya Pradesh, India"},
  {"name": "Bhopal", "region": "Madhya Pradesh, India"},
  {"name": "Bhubaneswar", "region": "Odisha, India"},
  {"name": "Bhuj", "region": "Gujarat, India"},
  {"name": "Bijapur", "region": "Karnataka, India"},
  {"name": "Bikaner", "region": "Rajasthan, India"},
  {"name": "Bir Billing", "region": "Himachal Pradesh, India"},
  {"name": "Bodh Gaya", "region": "Bihar, India"},
  {"name": "Bolpur", "region": "West Bengal, India"},
  {"name": "Chamba", "region": "Himachal Pradesh, India"},
  {"name": "Chandigarh", "region": "Punjab, India"},
  {"name": "Chennai", "region": "Tamil Nadu, India"},
  {"name": "Cherrapunji", "region": "Meghalaya, India"},
  {"name": "Chidambaram", "region": "Tamil Nadu, India"},
  {"name": "Chikmagalur", "region": "Karnataka, India"},
  {"name": "Chilika", "region": "Odisha, India"},
  {"name": "Chitrakoot", "region": "Madhya Pradesh, India"},
  {"name": "Chittorgarh", "region": "Rajasthan, India"},
  {"name": "Chopta", "region": "Uttarakhand, India"},
  {"name": "Coimbatore", "region": "Tamil Nadu, India"},
  {"name": "Cooch Behar", "region": "West Bengal, India"},
  {"name": "Coorg", "region": "Karnataka, India"},
  {"name": "Cuttack", "region": "Odisha, India"},
  {"name": "dalhousie", "region": "Himachal Pradesh, India"},
  {"name": "Darjeeling", "region": "India"},
  {"name": "Darjeeling", "region": "West Bengal, India"},
  {"name": "Dehradun", "region": "Uttarakhand, India"},
  {"name": "Delhi", "region": "Delhi, India"},
  {"name": "Deoghar", "region": "Jharkhand, India"},
  {"name": "Digha", "region": "West Bengal, India"},
  {"name": "Diskit", "region": "Ladakh, India"},
  {"name": "Diu", "region": "Daman and Diu, India"},
  {"name": "Dras", "region": "Ladakh, India"},
  {"name": "Dumboor", "region": "Tripura, India"},
  {"name": "Dwarka", "region": "Gujarat, India"},
  {"name": "Dz\u00c3\u00bckou Valley", "region": "Nagaland, India"},
  {"name": "Fatehpur Sikri", "region": "Uttar Pradesh, India"},
  {"name": "Gandhinagar", "region": "Gujarat, India"},
  {"name": "Gangtok", "region": "Sikkim, India"},
  {"name": "Goa", "region": "Goa, India"},
  {"name": "Goa", "region": "India"},
  {"name": "Gokarna", "region": "Karnataka, India"},
  {"name": "Greater Noida", "region": "Uttar Pradesh, India"},
  {"name": "Guntur", "region": "Andhra Pradesh, India"},
  {"name": "Gurugram", "region": "Haryana, India"},
  {"name": "Guwahati", "region": "Assam, India"},
  {"name": "Gwalior", "region": "Madhya Pradesh, India"},
  {"name": "Hajo", "region": "Assam, India"},
  {"name": "Halebidu", "region": "Karnataka, India"},
  {"name": "Hampi", "region": "India"},
  {"name": "Hampi", "region": "Karnataka, India"},
  {"name": "Haridwar", "region": "Uttarakhand, India"},
  {"name": "Havelock Island", "region": "Andaman and Nicobar Islands, India"},
  {"name": "Hemis", "region": "Ladakh, India"},
  {"name": "Hooghly", "region": "West Bengal, India"},
  {"name": "Hyderabad", "region": "Telangana, India"},
  {"name": "Indore", "region": "Madhya Pradesh, India"},
  {"name": "Jabalpur", "region": "Madhya Pradesh, India"},
  {"name": "Jaipur", "region": "India"},
  {"name": "Jaipur", "region": "Rajasthan, India"},
  {"name": "Jaisalmer", "region": "India"},
  {"name": "Jaisalmer", "region": "Rajasthan, India"},
  {"name": "Jalpaiguri", "region": "West Bengal, India"},
  {"name": "Jammu", "region": "Jammu and Kashmir, India"},
  {"name": "Jhansi", "region": "Uttar Pradesh, India"},
  {"name": "Jim Corbett", "region": "Uttarakhand, India"},
  {"name": "Jodhpur", "region": "Rajasthan, India"},
  {"name": "Joshimath", "region": "Uttarakhand, India"},
  {"name": "Junagadh", "region": "Gujarat, India"},
  {"name": "Kadapa", "region": "Andhra Pradesh, India"},
  {"name": "Kangra", "region": "Himachal Pradesh, India"},
  {"name": "Kanha", "region": "Madhya Pradesh, India"},
  {"name": "Kannur", "region": "Kerala, India"},
  {"name": "Kanpur", "region": "Uttar Pradesh, India"},
  {"name": "Kanyakumari", "region": "Tamil Nadu, India"},
  {"name": "Kargil", "region": "Ladakh, India"},
  {"name": "Kaziranga", "region": "Assam, India"},
  {"name": "Kedarnath", "region": "Uttarakhand, India"},
  {"name": "Kendujhar", "region": "Odisha, India"},
  {"name": "Keonjhar", "region": "Odisha, India"},
  {"name": "Kerala", "region": "India"},
  {"name": "Kevadia", "region": "Gujarat, India"},
  {"name": "Khajuraho", "region": "Madhya Pradesh, India"},
  {"name": "Kinnaur", "region": "Himachal Pradesh, India"},
  {"name": "Kishtwar", "region": "Jammu and Kashmir, India"},
  {"name": "Kochi", "region": "Kerala, India"},
  {"name": "Kodaikanal", "region": "Tamil Nadu, India"},
  {"name": "Kolhapur", "region": "Maharastra, India"},
  {"name": "Kolkata", "region": "West Bengal, India"},
  {"name": "Konark", "region": "Odisha, India"},
  {"name": "Kovalam", "region": "Kerala, India"},
  {"name": "Kozhikode", "region": "Kerala, India"},
  {"name": "Kufri", "region": "Himachal Pradesh, India"},
  {"name": "Kullu", "region": "Himachal Pradesh, India"},
  {"name": "Kumarakom", "region": "Kerala, India"},
  {"name": "Kurnool", "region": "Andhra Pradesh, India"},
  {"name": "Leh", "region": "Ladakh, India"},
  {"name": "Leh Ladakh", "region": "India"},
  {"name": "Lonavala", "region": "Maharastra, India"},
  {"name": "Lucknow", "region": "Uttar Pradesh, India"},
  {"name": "Madurai", "region": "Tamil Nadu, India"},
  {"name": "Mahabalipuram", "region": "Tamil Nadu, India"},
  {"name": "Majuli", "region": "Assam, India"},
  {"name": "Manali", "region": "Himachal Pradesh, India"},
  {"name": "Manali", "region": "India"},
  {"name": "Manas", "region": "Assam, India"},
  {"name": "Mandi", "region": "Himachal Pradesh, India"},
  {"name": "Mandu", "region": "Madhya Pradesh, India"},
  {"name": "Mangalore", "region": "Karnataka, India"},
  {"name": "Manikaran", "region": "Himachal Pradesh, India"},
  {"name": "Matheran", "region": "Maharashtra, India"},
  {"name": "Mathura", "region": "Uttar Pradesh, India"},
  {"name": "McLeod Ganj", "region": "Himachal Pradesh, India"},
  {"name": "Meerut", "region": "Uttar Pradesh, India"},
  {"name": "Meghalaya", "region": "India"},
  {"name": "Mount Abu", "region": "Rajasthan, India"},
  {"name": "Mumbai", "region": "Maharastra, India"},
  {"name": "Munnar", "region": "India"},
  {"name": "Munnar", "region": "Kerala, India"},
  {"name": "Murshidabad", "region": "West Bengal, India"},
  {"name": "Murudeshwar", "region": "Karnataka, India"},
  {"name": "Mussoorie", "region": "Uttarakhand, India"},
  {"name": "Mysore", "region": "India"},
  {"name": "Mysore", "region": "Karnataka, India"},
  {"name": "Nagpur", "region": "Maharastra, India"},
  {"name": "Nainital", "region": "Uttarakhand, India"},
  {"name": "Namchi", "region": "Sikkim, India"},
  {"name": "Narkanda", "region": "Himachal Pradesh, India"},
  {"name": "Nashik", "region": "Maharastra, India"},
  {"name": "Neil Island", "region": "Andaman and Nicobar Islands, India"},
  {"name": "Nelliyampathy", "region": "Kerala, India"},
  {"name": "New Delhi", "region": "Delhi, India"},
  {"name": "Noida", "region": "Uttar Pradesh, India"},
  {"name": "Nubra Valley", "region": "Ladakh, India"},
  {"name": "Ooty", "region": "India"},
  {"name": "Ooty", "region": "Tamil Nadu, India"},
  {"name": "Orchha", "region": "Madhya Pradesh, India"},
  {"name": "Pachmarhi", "region": "Madhya Pradesh, India"},
  {"name": "Pahalgam", "region": "Jammu and Kashmir, India"},
  {"name": "Palampur", "region": "Himachal Pradesh, India"},
  {"name": "Patna", "region": "Bihar, India"},
  {"name": "Pelling", "region": "Sikkim, India"},
  {"name": "Pondicherry", "region": "India"},
  {"name": "Porbandar", "region": "Uttar Pradesh, India"},
  {"name": "Port Blair", "region": "Andaman and Nicobar Islands, India"},
  {"name": "Puducherry", "region": "Puducherry, India"},
  {"name": "Pune", "region": "Maharastra, India"},
  {"name": "Puri", "region": "Odisha, India"},
  {"name": "Purulia", "region": "West Bengal, India"},
  {"name": "Pushkar", "region": "Rajasthan, India"},
  {"name": "Puttaparthi", "region": "Andhra Pradesh, India"},
  {"name": "Rajahmundry", "region": "Andhra Pradesh, India"},
  {"name": "Rameswaram", "region": "Tamil Nadu, India"},
  {"name": "Ranchi", "region": "Jharkhand, India"},
  {"name": "Ranikhet", "region": "Uttarakhand, India"},
  {"name": "Rann of Kutch", "region": "Gujarat, India"},
  {"name": "Ratnagiri", "region": "Maharastra, India"},
  {"name": "Ravangla", "region": "Sikkim, India"},
  {"name": "Rishikesh", "region": "India"},
  {"name": "Rishikesh", "region": "Uttarakhand, India"},
  {"name": "Rourkela", "region": "Odisha, India"},
  {"name": "Sambalpur", "region": "Odisha, India"},
  {"name": "Sarnath", "region": "Uttar Pradesh, India"},
  {"name": "Satara", "region": "Maharashtra, India"},
  {"name": "Sawai Madhopur", "region": "Rajasthan, India"},
  {"name": "Shimla", "region": "Himachal Pradesh, India"},
  {"name": "Shimla", "region": "India"},
  {"name": "Shirdi", "region": "Maharastra, India"},
  {"name": "Shivamogga", "region": "Karnataka, India"},
  {"name": "Shoja", "region": "Himachal Pradesh, India"},
  {"name": "Siliguri", "region": "West Bengal, India"},
  {"name": "Sivasagar", "region": "Assam, India"},
  {"name": "Somnath", "region": "Gujarat, India"},
  {"name": "Spiti Valley", "region": "Himachal Pradesh, India"},
  {"name": "Srinagar", "region": "India"},
  {"name": "Srinagar", "region": "Jammu and Kashmir, India"},
  {"name": "Srisailam", "region": "Andhra Pradesh, India"},
  {"name": "Sundarbans", "region": "West Bengal, India"},
  {"name": "Tarkarli", "region": "Maharashtra, India"},
  {"name": "Tawang", "region": "Arunachal Pradesh, India"},
  {"name": "Thanjavur", "region": "Tamil Nadu, India"},
  {"name": "Thekkady", "region": "Kerala, India"},
  {"name": "Thiruvananthapuram", "region": "Kerala, India"},
  {"name": "Tirunelveli", "region": "Tamil Nadu, India"},
  {"name": "Udaipur", "region": "India"},
  {"name": "Udaipur", "region": "Rajasthan, India"},
  {"name": "Udhampur", "region": "Jammu and Kashmir, India"},
  {"name": "Ujjain", "region": "Madhya Pradesh, India"},
  {"name": "Unakoti", "region": "Tripura, India"},
  {"name": "Uttarkashi", "region": "Uttarakhand, India"},
  {"name": "Vadodara", "region": "Gujarat, India"},
  {"name": "Varanasi", "region": "India"},
  {"name": "Varanasi", "region": "Uttar Pradesh, India"},
  {"name": "Varkala", "region": "Kerala, India"},
  {"name": "Vijayawada", "region": "Andhra Pradesh, India"},
  {"name": "Visakhapatnam", "region": "Andhra Pradesh, India"},
  {"name": "Vizianagaram", "region": "Andhra Pradesh, India"},
  {"name": "Vrindavan", "region": "Uttar Pradesh, India"},
  {"name": "Wayanad", "region": "Kerala, India"},
  {"name": "Yercaud", "region": "Tamil Nadu, India"},
];
